# Generated by Django 5.0.2 on 2024-02-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_bookingdate_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuItem',
        ),
    ]
